services:
  postgres-db:
    container_name: etapa3
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=policia_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  